### ISSUE TITLE
Add Support for 5-Variable Karnaugh Maps

### ISSUE THREAD

**Issue by Agentalpha50** [VarunMusham/Karnaugh-Map-Solver#1]
Hello,

First of all, thank you for developing and maintaining this helpful tool for solving Karnaugh maps. It has been incredibly useful for my studies and projects.

However, I have encountered a limitation with the current implementation. The tool currently does not support solving Karnaugh maps with 5 variables. Given the increasing complexity of problems I am working on, the ability to handle 5-variable Karnaugh maps would be immensely beneficial.

Feature Request:

* Add support for 5-variable Karnaugh maps.
* Ensure that the user interface is updated to accommodate the additional variable and its corresponding cells.
* Update the logic for simplification to handle 5-variable expressions accurately.
This feature would greatly enhance the tool's utility and help users dealing with more complex boolean expressions.

Thank you for considering this request. I look forward to your response and am willing to assist in testing the new feature if needed.

**Comment by VarunMusham** [comment]
Yeah Sure
